name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build, run_release, run_build_pspsdk, run_release_pspsdk]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macOS-11, ubuntu-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Install on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get -y install gettext texinfo bison flex libncurses5-dev libgmp3-dev libmpfr-dev libmpc-dev

    - name: Install on Mac
      if: startsWith( matrix.os, 'macOS' )
      run: |
        brew update
        brew install gettext texinfo bison flex gnu-sed ncurses gsl gmp mpfr

    - name: Runs all stages
      run: |
        export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
        export PSPDEV=$PWD/pspdev
        export PATH=$PATH:$PSPDEV/bin
        ./toolchain.sh
